### ISSUE TITLE
Installation instruction in README could refer to the v2 package

### ISSUE THREAD

**Issue by zachczx** [rezakhademix/govalidator#112]
I thought to mention this very minor point - the readme currently states 

`go get github.com/rezakhademix/govalidator`

but that installs 1.1.3, instead it could be told as 

`go get github.com/rezakhademix/govalidator/v2`

Hope this helps!

**Comment by rezakhademix** [comment]
Thanks!
I forgot to update the installation. You’re absolutely right, and I’ve fixed it!
