### ISSUE TITLE
Unclear README

### ISSUE THREAD

**Issue by eccles** [rezakhademix/govalidator#114]
The examples use a method c.Bind() without a clear explanation.

Suggestion - add an examples directory with worked examples using a main.go that the user can execute in go playground would be nice.

**Desktop (please complete the following information):**
 - Ubuntu 22.04
 - Brave

**Additional context**
where does c.Bind() or c.ShouldBind() come from?

**Comment by rezakhademix** [comment]
Hi, Thanks for your sharing your opinion.

I will update readme.md for a better and more clearn explanation about using the govalidator packge.
The `c.Bind()` or `c.ShouldBind()` methods are from Gin, Echo and other net/http Golang frameworks for binding an http request body or uri to a golang struct.

Typically you can use anything or even just golang to read request values and then use govalidator to validate the request
